#!/bin/bash

parsing_dir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
current_dir=$(pwd)

# Function that prints out help details
show_usage() {
printf "\nUsage: autoScan [Options]\n \n "
echo "OPTIONS:"
echo "   -u [URL]: Set target to a URL"
printf "   -i [IP_Address]: Set target to an IP address\n \n "
echo "  -o [DIR/FILE]: Output file/where to save it"
echo "   -h: Prints out usage and options"
printf "   -t: Forces scan to use default gateway\n \n "
}

# Creates flag variables
h_flag='false'
o_flag=''
u_flag=''
i_flag=''
t_flag='false'

# Sets flag value when called upon
while getopts 'ho:u:i:tv' flag; do
case "${flag}" in
h) h_flag='true' ;;
o) o_flag="${OPTARG}" ;;
u) u_flag="${OPTARG}" ;;
i) i_flag="${OPTARG}" ;;
t) t_flag='true' ;;
esac
done

# Prints usage guide if h flag is true
if [ $h_flag == true ]; then
show_usage
exit
fi

# Sets output directory if selected
if [ ! -z $o_flag ]; then
save_directory=$o_flag
set_save_later=False
else
set_save_later=True
fi

# Checks to see if an IP was given
if [ -z $u_flag ] && [ -z $i_flag ]; then
echo "Invalid, must use minimum -i or -u"
exit
fi

# Function that checks if host is up
ip-check() {
ping -c 1 $verify_ip > $parsing_dir/host-check.txt 2>/dev/null
mapfile -t hostline < $parsing_dir/host-check.txt
verify=$(echo ${hostline[0]} | cut -d" " -f1)
if [ -z $verify ]; then
echo "Host is down or does not exist"
exit
fi
}

# Converts url to ip if u flag is given
if [ ! -z $u_flag ]; then
verify_ip=$u_flag
ip-check
nslookup $u_flag > $parsing_dir/nslookup.txt
cat $parsing_dir/nslookup.txt|grep -v "192.168."|grep "Address:"|cut -d" " -f2 > $parsing_dir/nslookup_ips.txt
mapfile -t ips <$parsing_dir/nslookup_ips.txt
ip=${ips[0]}
if [ $set_save_later == True ]; then
save_directory="$current_dir/$u_flag"
fi
fi

# check to see if nslookup worked
if [ ! -z $u_flag ]; then
nslookup_empty_check=$(head -n 1 $parsing_dir/nslookup_ips.txt)
if [ -z $nslookup_empty_check ]; then
echo -e "\e[0;31m[+] \e[0mInvalid URL!"
exit
fi
fi

# Sets ip if called upon
if [ ! -z $i_flag ]; then
verify_ip=$i_flag
ip-check
ip=$i_flag
if [ $set_save_later == True ]; then
save_directory="$current_dir/$i_flag"
fi
fi

# Check to see if nmap and masscan is installed
apt list --installed > $parsing_dir/installed_packages.txt 2>/dev/null
nmap_check=$(cat $parsing_dir/installed_packages.txt | grep "nmap/" | cut -d" " -f1 | head -n 1)
masscan_check=$(cat $parsing_dir/installed_packages.txt | grep "masscan/" | cut -d" " -f1 | head -n 1)

# Installs nmap if its not installed
if [ -z $nmap_check ]; then
echo -e "\e[0;31m[+] \e[0mNmap not found!";
echo -e "\e[1;34m[+] \e[0mInstalling..."
apt install nmap -y >/dev/null 2>/dev/null
else
echo -e "\e[1;34m[+] \e[0mNmap has been detected"
fi

# Installs masscan if its not installed
if [ -z $masscan_check ]; then
echo -e "\e[0;31m[+] \e[0mMasscan not detected!"
echo -e "\e[1;34m[+] \e[0mInstalling"
apt install masscan -y >/dev/null 2>/dev/null
else
echo -e "\e[1;34m[+] \e[0mMasscan has been detected"
fi

# Check to see if you are connected to a vpn
ifconfig | grep "flags" | cut -d":" -f1 > $parsing_dir/htb_tunnel.txt
tun0_check=$(cat $parsing_dir/htb_tunnel.txt | grep "tun0")

# Uses vpn tunnel in masscan if detected
if [ $t_flag == false ]; then
if [ ! -z $tun0_check ]; then
interface="-e tun0 "
ping_interface="-I tun0"
echo -e "\e[1;34m[+] \e[0mVPN tunnel detected"
fi
fi

# Check to make sure VPN isnt interfereing
if [ ! -z $tun0_check ]; then
ping -c 1 $ping_interface $ip > $parsing_dir/ping_test.txt
vpn_check=$(cat $parsing_dir/ping_test.txt | grep "received" | cut -d" " -f4)
if [ $vpn_check == 0 ]; then
echo -e "\e[0;31m[+] \e[0mUnable to connect to host!"
echo "If you are using a VPN try using script with/without -t"
exit
fi
fi

# Runs the masscan
echo -e "\e[1;34m[+] \e[0mStarting Scans..."
masscan $interface-p0-1000 --max-rate 500 $ip > $parsing_dir/masscan.txt 2>/dev/null
cat $parsing_dir/masscan.txt | cut -d" " -f4 | cut -d"/" -f1 > $parsing_dir/open_ports.txt
mapfile -t port < $parsing_dir/open_ports.txt
current=0

# Prints which ports are open, and makes list of them
while [ ! -z ${port[current]} ]; do
echo -e "\e[0;32m[+] \e[0mOpen port discovered ${port[current]}"
echo ${port[current]} >> $parsing_dir/port_list.txt
let current++
done

# Makes open ports into a variable
for port_count in $(cat $parsing_dir/port_list.txt); do
echo -n "$port_count," >> $parsing_dir/ports_to_scan.txt
done
nmap_ports=$(head -n 1 $parsing_dir/ports_to_scan.txt)

# Scans the open ports
nmap -A -p $nmap_ports $ip -oA $save_directory >/dev/null 2>/dev/null

# Checks to see if any ports were discovered
if [ -z ${port[0]} ]; then
echo -e "\e[0;31m[+] \e[0mNo open ports were discovered"
fi

echo -e "\e[1;34m[+] \e[0mFinished"
